### PR TITLE
added example ipynb for analyzing sequencing data in python

### PR DESCRIPTION
**Pull request by sonyahanson**
added example ipynb for analyzing sequencing data in python

### CODE REVIEW

**Comment by sonyahanson** [comment]
Gonna wait for somebody else to merge this, as this starts to be a real thing. Yay!

**Comment by sonyahanson** [comment]
If somebody could take a look at this and make sure it makes sense to at least one other person besides me, that'd be great. Feel free to make issues about things that are dumb, and not merge if you think it's too dumb. @MehtapIsik @steven-albanese @jchodera @lucelenie

**Comment by jchodera** [comment]
What file should we be looking at? Is it [this notebook](https://github.com/choderalab/PlasmidLibraryTools/blob/2b775c157b5e2924042943ecba092c86703d329c/scripts/T7-Term-verify-sequence.ipynb)?

**Comment by sonyahanson** [comment]
You should be looking at the entire repository, there is really not that much here... Just updated README to clarify what the `ipynb` is.

**Comment by sonyahanson** [comment]
I'm sure there are things that are unclear, which is why I want feedback from you guys. The purpose of this is to have (1) somewhere where we are storing our sequencing files, it seemed from the github was a good place for this according to our discussions on slack, and (2) so that we have a record of our conclusions on determining whether sequencing results confirm our expectations, since before this was just me or Lucelenie looking at the sequences in 'EditSeq' and making somewhat qualitative judgements.

I can paraphrase this in the `README.md` if that is helpful.

**Comment by steven-albanese** [comment]
How are you picking which reading frame to use? It's not necessarily clear in the notebook how you're doing that. Also, is it possible to have some kind of metric for what an acceptable alignment is? Eyeballing the alignment will be hard when looking for a point mutant. 

I also mentioned this in #13, but it would be great to have this written up as a script to use on the cluster once we progress beyond the example stage!

**Comment by sonyahanson** [comment]
Right now the reading frame is picked manually, e.g. the 2 in`sequencing_result = rev_sequencing_pick_frame(filename,2)` in line 29.

This is certainly not what we want to do longterm. I've made an issue, to find something that will automatically find the ORF for us, with some links I found when I was initially going through this.

**Comment by sonyahanson** [comment]
If someone can merge this, then we can start working on going through and make this more of script-based pipeline that maybe even automatically adds our sequences back to the CSV file once they've been analyzed!

**Comment by steven-albanese** [comment]
ok, thanks for the info I'll take another pass through the issue tracker. Merging this now

**Pull request merged**
